openapi: 3.1.0
info:
  title: "MachikanNumberAPI"
  version: "1.0.0"
  description: "This is a MachikanNumberAPI"

servers:
  - url: "http://localhost: 3000"
    description: "開発環境"

tags:
  - name: "shops"
    description: "ショップ情報"
  - name: "items"
    description: "商品情報"
  - name: "orders"
    description: "注文情報"
  - name: "events"
    description: "イベント情報"


paths:
  "/shops":
    post:
      tags:
        - "shops"
      summary: "ショップ登録"
      description: "ショップを登録する"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "ショップ名"
                start_at:
                  type: "string"
                  format: "date-time"
                end_at:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                  description: "説明"
      responses:
        "201":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shop"
  "/shops/{shop_id}":
    get:
      tags:
        - "shops"
      summary: "ショップ情報取得"
      description: "ショップ情報を取得する"
      parameters:
        - name: "shop_id"
          in: "path"
          description: "ショップID"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shop"
        "404":
          description: "ショップが見つからない"
    patch:
      tags:
        - "shops"
      summary: "ショップ情報更新"
      description: "ショップ情報を更新する"
      parameters:
        - name: "shop_id"
          in: "path"
          description: "ショップID"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "ショップ名"
                start_at:
                  type: "string"
                  format: "date-time"
                end_at:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                  description: "説明"
  "/orders":
    post:
      tags:
        - "orders"
      summary: "注文登録"
      description: "注文を登録する"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                shop_id:
                  type: "string"
                  format: "uuid"
                  description: "ショップID"
                card_number:
                  type: "string"
                  description: "カード番号"
                items:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      item_id:
                        type: "string"
                        description: "商品ID"
                      count:
                        type: "integer"
                        description: "個数"
      responses:
        "201":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/order"
  "/orders/{shop_id}":
    get:
      tags:
        - "orders"
      summary: "注文情報取得"
      description: "店の全ての注文情報を取得する"
      parameters:
        - name: "shop_id"
          in: "path"
          description: "ショップID"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/order"
        "404":
          description: "注文が見つからない"
  "/orders/{order_id}":
    delete:
      tags:
        - "orders"
      summary: "注文削除"
      description: "注文を削除する"
      parameters:
        - name: "order_id"
          in: "path"
          description: "注文ID"
          required: true
          schema:
            type: "string"
      responses:
        "204":
          description: "成功"
  "/items":
    post:
      tags:
        - "items"
      summary: "商品登録"
      description: "商品を登録する"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                shop_id:
                  type: "string"
                  format: "uuid"
                  description: "ショップID"
                name:
                  type: "string"
                  description: "商品名"
                price:
                  type: "integer"
                  description: "価格"
                time:
                  type: "integer"
                  description: "必要時間"
      responses:
        "201":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
  "/items/{shop_id}":
    get:
      tags:
        - "items"
      summary: "商品情報取得"
      description: "店の全ての商品情報を取得する"
      parameters:
        - name: "shop_id"
          in: "path"
          description: "ショップID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/item"
        "404":
          description: "商品が見つからない"
  "/items/{item_id}":
    patch:
      tags:
        - "items"
      summary: "商品情報更新"
      description: "商品情報を更新する"
      parameters:
        - name: "item_id"
          in: "path"
          description: "商品ID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "商品名"
                price:
                  type: "integer"
                  description: "価格"
                time:
                  type: "integer"
                  description: "必要時間"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
    delete:
      tags:
        - "items"
      summary: "商品削除"
      description: "商品を削除する"
      parameters:
        - name: "item_id"
          in: "path"
          description: "商品ID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "204":
          description: "成功"
  "/events":
    post:
      tags:
        - "events"
      summary: "イベント登録"
      description: "イベントを登録する"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "イベント名"
                start_at:
                  type: "string"
                  format: "date-time"
                end_at:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                  description: "説明"
      responses:
        "201":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
  "/events/{event_id}":
    get:
      tags:
        - "events"
      summary: "イベント情報取得"
      description: "イベント情報を取得する"
      parameters:
        - name: "event_id"
          in: "path"
          description: "イベントID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        "404":
          description: "イベントが見つからない"
    patch:
      tags:
        - "events"
      summary: "イベント情報更新"
      description: "イベント情報を更新する"
      parameters:
        - name: "event_id"
          in: "path"
          description: "イベントID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  description: "イベント名"
                start_at:
                  type: "string"
                  format: "date-time"
                end_at:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                  description: "説明"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
    delete:
      tags:
        - "events"
      summary: "イベント削除"
      description: "イベントを削除する"
      parameters:
        - name: "event_id"
          in: "path"
          description: "イベントID"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "204":
          description: "成功"

components:
  schemas:
    shop:
      type: "object"
      properties:
        shop_id:
          type: "string"
          format: "uuid"
          description: "ショップID"
        name:
          type: "string"
          description: "ショップ名"
        start_at:
          type: "string"
          format: "date-time"
        end_at:
          type: "string"
          format: "date-time"
        description:
          type: "string"
          description: "説明"
      required:
        - shop_id
        - name
    item:
      type: "object"
      properties:
        item_id:
          type: "string"
          format: "uuid"
          description: "商品ID"
        name:
          type: "string"
          description: "商品名"
        price:
          type: "integer"
          description: "価格"
        time:
          type: "integer"
          description: "必要時間"
      required:
        - item_id
        - name
        - price
        - time
    order:
      type: "object"
      properties:
        order_id:
          type: "string"
          format: "uuid"
          description: "注文ID"
        shop_id:
          type: "string"
          format: "uuid"
          description: "ショップID"
        card_number:
          type: "string"
          description: "カード番号"
        create_at:
          type: "string"
          format: "date-time"
          description: "注文時間"
        items:
          type: "array"
          items:
            type: "object"
            properties:
              item_id:
                type: "string"
                format: "uuid"
                description: "商品ID"
              count:
                type: "integer"
                description: "個数"
      required:
        - order_id
        - shop_id
        - items
        - card_number
        - create_at
    event:
      type: "object"
      properties:
        event_id:
          type: "string"
          format: "uuid"
          description: "イベントID"
        name:
          type: "string"
          description: "イベント名"
        shops:
          type: "array"
          items:
            $ref: "#/components/schemas/shop"
        start_at:
          type: "string"
          format: "date-time"
          description: "開始時間"
        end_at:
          type: "string"
          format: "date-time"
          description: "終了時間"
        description:
          type: "string"
          description: "説明"
      required:
        - event_id
        - name